import{a as h,S as p,i as c}from"./assets/vendor-6e0bf343.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const L="https://pixabay.com/api/",b="39287667-f1a1553e63cd5dc6035e5c951",u={url:L,params:{key:b,q:"",image_type:"photo",orientation:"horizontal",page:1,per_page:15},getPhotos(a=this.params.q){return this.params.q=a,h.get(this.url,{params:{...this.params,page:this.params.page++}})}};function y(a){return a.map(v).join("")}function v(a){const{largeImageURL:s,webformatURL:n,tags:l,likes:e,views:o,comments:i,downloads:g}=a;return`<div class="gallery__item">
        <a class="gallery__link" href="${s}">
          <img class="gallery__image" src="${n}" alt="${l}" loading="lazy"/>
        </a>
        <div class="gallery__info">
          <p class="gallery__info-item">
            <b>Likes ${e}</b>
          </p>
          <p class="gallery__info-item">
            <b>Views ${o}</b>
          </p>
          <p class="gallery__info-item">
            <b>Comments ${i}</b>
          </p>
          <p class="gallery__info-item">
            <b>Downloads ${g}</b>
          </p>
        </div>
      </div>`}function f(a,s){a.insertAdjacentHTML("beforeend",s)}const t={gallery:document.querySelector(".gallery"),form:document.querySelector("form"),loadMoreBtn:document.querySelector(".load-more"),searchButton:document.querySelector("#search-form button")},r={totalImagesUploaded:0,classLists:{visuallyHidden:"visually-hidden"}};console.log(r);console.log(u);d(t.loadMoreBtn,r.classLists.visuallyHidden);t.form.addEventListener("submit",_);t.loadMoreBtn.addEventListener("click",B);async function B(a){t.loadMoreBtn.textContent="Loading...";try{const{data:s}=await u.getPhotos(),{hits:n,totalHits:l}=s,e=y(n);f(t.gallery,e);const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();if(window.scrollBy({top:o*1.95,behavior:"smooth"}),new p(".gallery a",{}).refresh(),r.totalImagesUploaded+=15,r.totalImagesUploaded>=l){c.warning({message:"we're sorry? but you've reached the end of search result",position:"topRight"}),d(t.loadMoreBtn,r.classLists.visuallyHidden);return}}catch(s){c.warning({message:"we're sorry? but you've reached the end of search result",position:"topRight"}),console.log("ERROR",s)}finally{t.loadMoreBtn.textContent="Load more",console.log(r),console.log(u)}}async function _(a){a.preventDefault();const{searchQuery:s}=t.form.elements,n=s.value.trim();if(!n){c.info({message:"Pleace, enter data to search",position:"topRight"});return}t.searchButton.disabled=!0,t.loadMoreBtn.textContent="Loading....",m(t.loadMoreBtn,r.classLists.visuallyHidden),t.gallery.innerHTML="",r.totalImagesUploaded=0,u.params.page=1;try{const{data:l}=await u.getPhotos(n),{hits:e,totalHits:o}=l;if(console.log(e),console.log(o),!o){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),t.loadMoreBtn.textContent="Load more",d(t.loadMoreBtn,r.classLists.visuallyHidden),t.searchButton.disabled=!1;return}c.success({message:`Hooray! We found ${o} images.`,position:"topRight"});const i=y(e);f(t.gallery,i),t.searchButton.disabled=!1,r.totalImagesUploaded=15,new p(".gallery a",{}).refresh(),t.loadMoreBtn.textContent="Load more",o<=15?d(t.loadMoreBtn,r.classLists.visuallyHidden):m(t.loadMoreBtn,r.classLists.visuallyHidden)}catch(l){console.log("ERROR",l),c.error({message:"Sorry there was an error",position:"topRight"}),t.searchButton.disabled=!1,d(t.loadMoreBtn,r.classLists.visuallyHidden)}}function d(a,s){a.classList.add(s)}function m(a,s){a.classList.remove(s)}
//# sourceMappingURL=commonHelpers.js.map
